services:
  http-server-projeto-korp:
    build: .
    networks:
      - projeto-korp-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    networks:
      - projeto-korp-network
    ports:
      - "80:80"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d:ro
    depends_on:
      - http-server-projeto-korp
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    depends_on:
      - http-server-projeto-korp
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - projeto-korp-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
      - http-server-projeto-korp
    networks:
      - projeto-korp-network
    restart: unless-stopped

networks:
  projeto-korp-network:
    driver: bridge